name: Build ZeroIQMachine

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip uninstall -y numpy
        pip install numpy==1.26.4

    - name: Build ZeroIQMachine executable
      run: |
        pyinstaller --onefile --noconsole \
          --name "ZeroIQMachine" \
          --add-data "assets:assets" \
          --add-data "ui:ui" \
          main.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZeroIQMachine-${{ matrix.os }}
        path: dist/*
